"""Demand generator — bridges trained model artifacts to the simulation loop.

environment.py imports DemandGenerator from here.

Design
------
- Loads a trained LightGBM (.bin) or XGBoost (.json) artifact from disk.
- For XGBoost: reads xgb_features_{store_id}.json to get the exact ordered
  feature list used during Colab training, then builds the input row in that
  exact order.
- Warm-starts the rolling sales buffer from real M5 data (last 28 days of
  actual store-level daily totals) so lag_7 / lag_14 / lag_28 and all
  rolling stats are real numbers on day 0, not zeros.
- After each prediction the buffer rolls forward with the new predicted value,
  so the lag features stay live throughout the simulation.
- Falls back to a realistic statistical baseline (Poisson + trend) if no
  artifact is found, so the simulation still runs without trained models.
- Applies ExternalFactors multipliers so holidays/weekends/weather affect demand.
- Exposes get_demand(day) and get_forecast_range(day, days) used by
  SmartInventoryAgent.
"""

from __future__ import annotations

import json
import os
import warnings
from collections import deque
from datetime import datetime, timedelta
from pathlib import Path
from typing import Deque, Dict, List, Optional

import numpy as np
import pandas as pd

from src.simulation.external_factors import ExternalFactorsGenerator

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
MODEL_DIR = Path(os.getenv("MODEL_DIR", "models"))

LGBM_PATTERN          = "lgb_model_{store_id}.bin"
XGB_PATTERN           = "xgb_model_{store_id}.json"
XGB_FEATURES_PATTERN  = "xgb_features_{store_id}.json"

# Warm-start data: real M5 last-28-days store-level daily totals.
# Place this file at models/m5_warmstart_sales.json
# (generated by scripts/build_warmstart.py or shipped directly).
WARMSTART_PATH = MODEL_DIR / "m5_warmstart_sales.json"

XGB_STORE_IDS = (
    "CA_1", "CA_2", "CA_3", "CA_4",
    "TX_1", "TX_2", "TX_3",
    "WI_1", "WI_2", "WI_3",
)

# ---------------------------------------------------------------------------
# Warm-start loader
# ---------------------------------------------------------------------------

def _load_warmstart_buffer(store_id: str) -> Optional[Deque[float]]:
    """Load the last 28 days of real M5 daily sales for *store_id*.

    Returns a deque(maxlen=28) seeded with real historical values so that
    lag_7, lag_14, lag_28, rolling_mean_*, and rolling_std_* features start
    with accurate numbers instead of zeros.

    Returns None (with a warning) if the warm-start file is missing, so the
    caller can fall back to the statistical baseline seed.
    """
    if not WARMSTART_PATH.exists():
        warnings.warn(
            f"DemandGenerator[{store_id}]: warm-start file not found at "
            f"{WARMSTART_PATH}. Lag features will be seeded from the "
            f"statistical baseline instead of real M5 data."
        )
        return None
    try:
        with open(WARMSTART_PATH, "r", encoding="utf-8") as fh:
            data = json.load(fh)
        store_data = data.get(store_id)
        if store_data is None:
            warnings.warn(
                f"DemandGenerator[{store_id}]: store not found in warm-start "
                f"file. Known stores: {list(data.keys())}"
            )
            return None
        buf: Deque[float] = deque(maxlen=28)
        buf.extend(float(v) for v in store_data[-28:])
        return buf
    except Exception as exc:
        warnings.warn(
            f"DemandGenerator[{store_id}]: failed to load warm-start data: {exc}"
        )
        return None


# ---------------------------------------------------------------------------
# Model loaders
# ---------------------------------------------------------------------------

def _load_lgbm(path: Path):
    """Load a LightGBM Booster from a .bin artifact."""
    try:
        import lightgbm as lgb  # type: ignore
        return lgb.Booster(model_file=str(path))
    except Exception as exc:
        warnings.warn(f"DemandGenerator: failed to load LightGBM from {path}: {exc}")
        return None


def _load_xgb(path: Path):
    """Load an XGBoost Booster from a .json artifact."""
    try:
        import xgboost as xgb  # type: ignore
        booster = xgb.Booster()
        booster.load_model(str(path))
        return booster
    except Exception as exc:
        warnings.warn(f"DemandGenerator: failed to load XGBoost from {path}: {exc}")
        return None


def _load_xgb_features(store_id: str) -> Optional[List[str]]:
    """Load the ordered feature list for an XGBoost model from its companion JSON.

    File expected at models/xgb_features_{store_id}.json.
    Must contain a JSON array of feature name strings in training order.
    Returns None (with a warning) if missing or malformed.
    """
    path = MODEL_DIR / XGB_FEATURES_PATTERN.format(store_id=store_id)
    if not path.exists():
        warnings.warn(
            f"DemandGenerator[{store_id}]: XGBoost feature file not found at "
            f"{path}. Will fall back to LightGBM or statistical baseline."
        )
        return None
    try:
        with open(path, "r", encoding="utf-8") as fh:
            features = json.load(fh)
        if not isinstance(features, list) or not all(isinstance(f, str) for f in features):
            warnings.warn(
                f"DemandGenerator[{store_id}]: {path} must contain a JSON "
                f"array of strings."
            )
            return None
        return features
    except Exception as exc:
        warnings.warn(
            f"DemandGenerator[{store_id}]: failed to parse feature file: {exc}"
        )
        return None


# ---------------------------------------------------------------------------
# Feature builders
# ---------------------------------------------------------------------------

def _build_lgbm_features(day_index: int, date: datetime) -> np.ndarray:
    """Build the 13-feature vector used by the LightGBM models.

    Features (in order):
        0  day_of_week      (0=Mon … 6=Sun)
        1  day_of_month     (1-31)
        2  month            (1-12)
        3  week_of_year     (1-53)
        4  is_weekend       (0/1)
        5  is_month_start   (0/1)
        6  is_month_end     (0/1)
        7  quarter          (1-4)
        8  day_index        (simulation day — encodes trend)
        9  sin_day_of_year  (annual seasonality)
        10 cos_day_of_year
        11 sin_week         (weekly seasonality)
        12 cos_week
    """
    dow        = date.weekday()
    dom        = date.day
    month      = date.month
    woy        = date.isocalendar()[1]
    is_weekend = int(dow >= 5)
    is_ms      = int(dom == 1)
    is_me      = int(
        dom == (date.replace(month=month % 12 + 1, day=1) - timedelta(days=1)).day
    )
    quarter    = (month - 1) // 3 + 1
    doy        = date.timetuple().tm_yday
    sin_doy    = np.sin(2 * np.pi * doy / 365.25)
    cos_doy    = np.cos(2 * np.pi * doy / 365.25)
    sin_week   = np.sin(2 * np.pi * dow / 7)
    cos_week   = np.cos(2 * np.pi * dow / 7)

    return np.array([[
        dow, dom, month, woy, is_weekend, is_ms, is_me,
        quarter, day_index, sin_doy, cos_doy, sin_week, cos_week,
    ]], dtype=np.float32)


def _build_xgb_row(
    day_index: int,
    date: datetime,
    feature_names: List[str],
    sales_buffer: Deque[float],
) -> "xgb.DMatrix":  # type: ignore[name-defined]
    """Build an XGBoost DMatrix row using the exact feature order from training.

    Lag and rolling features are computed from *sales_buffer*, which is a
    deque(maxlen=28) of the last 28 days of actual/predicted store-level
    daily sales.  On simulation day 0 this is seeded from real M5 data, so
    the model sees realistic numbers from the very first prediction.

    Parameters
    ----------
    day_index : int
        Simulation day offset from start_date.
    date : datetime
        Calendar date for this prediction.
    feature_names : list[str]
        Ordered list from xgb_features_{store_id}.json.
    sales_buffer : deque[float]
        Rolling window of the last 28 days of store sales.
        Must contain at least 28 entries (guaranteed after warm-start).

    Returns
    -------
    xgb.DMatrix
        Single-row DMatrix ready for booster.predict().
    """
    import xgboost as xgb  # type: ignore

    # ---- calendar ----
    dow     = date.weekday()
    dom     = date.day
    month   = date.month
    year    = date.year
    woy     = date.isocalendar()[1]
    doy     = date.timetuple().tm_yday
    quarter = (month - 1) // 3 + 1

    # ---- lag features from rolling buffer ----
    # Buffer stores days oldest→newest; index [-1] = yesterday.
    buf = list(sales_buffer)   # snapshot — do not mutate here
    lag_1  = buf[-1]  if len(buf) >= 1  else 0.0
    lag_7  = buf[-7]  if len(buf) >= 7  else 0.0
    lag_14 = buf[-14] if len(buf) >= 14 else 0.0
    lag_28 = buf[-28] if len(buf) >= 28 else 0.0

    # ---- rolling statistics ----
    win7  = buf[-7:]  if len(buf) >= 7  else buf
    win14 = buf[-14:] if len(buf) >= 14 else buf
    win28 = buf[-28:] if len(buf) >= 28 else buf

    rolling_mean_7   = float(np.mean(win7))   if win7  else 0.0
    rolling_mean_14  = float(np.mean(win14))  if win14 else 0.0
    rolling_mean_28  = float(np.mean(win28))  if win28 else 0.0
    rolling_std_7    = float(np.std(win7))    if len(win7)  > 1 else 0.0
    rolling_std_14   = float(np.std(win14))   if len(win14) > 1 else 0.0
    rolling_std_28   = float(np.std(win28))   if len(win28) > 1 else 0.0
    rolling_median_7 = float(np.median(win7)) if win7  else 0.0

    # ---- full lookup (keys must match xgb_features_{store_id}.json exactly) ----
    _lookup: Dict[str, float] = {
        # calendar basics
        "day_of_week":          float(dow),
        "dayofweek":            float(dow),
        "day_of_month":         float(dom),
        "dayofmonth":           float(dom),
        "month":                float(month),
        "year":                 float(year),
        "week_of_year":         float(woy),
        "weekofyear":           float(woy),
        "day_of_year":          float(doy),
        "dayofyear":            float(doy),
        "quarter":              float(quarter),
        "day_index":            float(day_index),

        # binary calendar flags
        "is_weekend":           float(dow >= 5),
        "is_month_start":       float(dom == 1),
        "is_month_end":         float(
            dom == (date.replace(month=month % 12 + 1, day=1) - timedelta(days=1)).day
        ),
        "is_quarter_start":     float(month in (1, 4, 7, 10) and dom == 1),
        "is_quarter_end":       float(month in (3, 6, 9, 12) and dom >= 28),
        "is_year_start":        float(month == 1 and dom == 1),
        "is_year_end":          float(month == 12 and dom == 31),

        # Fourier seasonality
        "sin_day_of_year":      float(np.sin(2 * np.pi * doy / 365.25)),
        "cos_day_of_year":      float(np.cos(2 * np.pi * doy / 365.25)),
        "sin_week":             float(np.sin(2 * np.pi * dow / 7)),
        "cos_week":             float(np.cos(2 * np.pi * dow / 7)),
        "sin_month":            float(np.sin(2 * np.pi * month / 12)),
        "cos_month":            float(np.cos(2 * np.pi * month / 12)),

        # lag features — NOW FROM REAL BUFFER, not zeros
        "lag_1":                lag_1,
        "lag_7":                lag_7,
        "lag_14":               lag_14,
        "lag_28":               lag_28,

        # rolling statistics — NOW FROM REAL BUFFER, not zeros
        "rolling_mean_7":       rolling_mean_7,
        "rolling_mean_14":      rolling_mean_14,
        "rolling_mean_28":      rolling_mean_28,
        "rolling_std_7":        rolling_std_7,
        "rolling_std_14":       rolling_std_14,
        "rolling_std_28":       rolling_std_28,
        "rolling_median_7":     rolling_median_7,

        # price features — unknown at inference, zero is the safest neutral
        # Replace with real price data if your simulation tracks prices.
        "sell_price":           0.0,
        "price_change":         0.0,
        "price_momentum":       0.0,
        "price_norm":           0.0,
    }

    row_values = [_lookup.get(name, 0.0) for name in feature_names]
    df = pd.DataFrame([row_values], columns=feature_names)
    return xgb.DMatrix(df)


# ---------------------------------------------------------------------------
# Statistical fallback
# ---------------------------------------------------------------------------

class _StatisticalBaseline:
    """Realistic fallback when no model artifact is available.

    Uses a Poisson process with:
    - Gentle upward trend (0.1 % per day)
    - Weekly seasonality (weekends +15 %)
    - Annual seasonality (Nov/Dec/Jan +20 %, Jun/Jul -10 %)
    - Per-store reproducible randomisation
    """

    def __init__(self, store_id: str, base_demand: float = 35.0, seed: int = 42):
        store_hash = hash(store_id) % (2 ** 31)
        self.rng = np.random.default_rng(seed ^ store_hash)
        self.base = base_demand

    def predict(self, day_index: int, date: datetime) -> float:
        trend    = 1.0 + 0.001 * day_index
        dow      = date.weekday()
        weekend  = 1.15 if dow >= 5 else 1.0
        month    = date.month
        seasonal = 1.20 if month in (11, 12, 1) else (0.90 if month in (6, 7) else 1.0)
        mu       = self.base * trend * weekend * seasonal
        return float(self.rng.poisson(max(1.0, mu)))


# ---------------------------------------------------------------------------
# DemandGenerator
# ---------------------------------------------------------------------------

class DemandGenerator:
    """Load a trained model artifact and produce per-day demand for one store.

    Key design decisions
    --------------------
    1. XGBoost models require a companion xgb_features_{store_id}.json giving
       the exact feature order used during training.  If that file is absent
       the XGB model is skipped entirely rather than predicting with wrong features.

    2. Lag / rolling features are seeded from real M5 historical sales
       (models/m5_warmstart_sales.json) so day-0 predictions are accurate.
       After each prediction the buffer rolls forward automatically.

    3. If no artifact or warm-start data is found the generator falls back to
       a Poisson-based statistical baseline so the simulation always runs.

    Parameters
    ----------
    store_id : str
        e.g. "CA_1".  Determines which artifact files are loaded.
    model_type : str
        "lgbm" (default) or "xgb".
    external_factors : ExternalFactorsGenerator
        Shared instance from the simulator — provides demand multipliers.
    start_date : datetime
        Calendar date for simulation day 0.  Defaults to today.
    seed : int
        Used by the statistical fallback only.
    base_demand : float
        Baseline demand (units/day) for the statistical fallback.
    """

    def __init__(
        self,
        store_id: str,
        model_type: str = "lgbm",
        external_factors: Optional[ExternalFactorsGenerator] = None,
        start_date: Optional[datetime] = None,
        seed: int = 42,
        base_demand: float = 35.0,
    ) -> None:
        self.store_id         = store_id
        self.model_type       = model_type.lower()
        self.external_factors = external_factors or ExternalFactorsGenerator(seed=seed)
        self.start_date       = start_date or datetime.now().replace(
            hour=0, minute=0, second=0, microsecond=0
        )
        self._model           = None
        self._xgb_features: Optional[List[str]] = None
        self._baseline        = _StatisticalBaseline(store_id, base_demand=base_demand, seed=seed)
        self._using_model     = False

        # Rolling sales buffer: deque(maxlen=28) of store-level daily totals.
        # Seeded from real M5 data; updated after every prediction.
        self._sales_buffer: Deque[float] = self._init_sales_buffer(seed, base_demand)

        self._try_load_model()

    # ------------------------------------------------------------------
    # Initialisation helpers
    # ------------------------------------------------------------------

    def _init_sales_buffer(self, seed: int, base_demand: float) -> Deque[float]:
        """Return a 28-entry deque seeded with real M5 data if available.

        Falls back to synthetic values from the statistical baseline so the
        buffer is always full on day 0 regardless of file availability.
        """
        buf = _load_warmstart_buffer(self.store_id)
        if buf is not None and len(buf) == 28:
            return buf

        # Fallback: generate 28 synthetic days before day 0 using the baseline
        warnings.warn(
            f"DemandGenerator[{self.store_id}]: seeding lag buffer from "
            f"statistical baseline (real M5 warm-start unavailable)."
        )
        fb = _StatisticalBaseline(self.store_id, base_demand=base_demand, seed=seed)
        start = self.start_date - timedelta(days=28)
        synthetic: Deque[float] = deque(maxlen=28)
        for i in range(28):
            d = start + timedelta(days=i)
            synthetic.append(fb.predict(-(28 - i), d))
        return synthetic

    def _try_load_model(self) -> None:
        """Attempt to load the model artifact for this store.

        XGBoost: requires both the .json model AND the companion feature file.
        If the feature file is missing the model is NOT loaded (wrong features
        are worse than no model).
        """
        if self.model_type == "lgbm":
            path = MODEL_DIR / LGBM_PATTERN.format(store_id=self.store_id)
            if path.exists():
                m = _load_lgbm(path)
                if m is not None:
                    self._model = m
                    self._using_model = True
                    return

        elif self.model_type == "xgb":
            model_path = MODEL_DIR / XGB_PATTERN.format(store_id=self.store_id)
            if not model_path.exists():
                warnings.warn(
                    f"DemandGenerator[{self.store_id}]: XGBoost model not found "
                    f"at {model_path}. Using statistical baseline."
                )
                return
            # Feature file must be loaded BEFORE the model — fail fast if missing
            feature_names = _load_xgb_features(self.store_id)
            if feature_names is None:
                warnings.warn(
                    f"DemandGenerator[{self.store_id}]: skipping XGBoost model "
                    f"because feature file is missing. Using statistical baseline."
                )
                return
            m = _load_xgb(model_path)
            if m is not None:
                self._model        = m
                self._xgb_features = feature_names
                self._using_model  = True
                return

        warnings.warn(
            f"DemandGenerator[{self.store_id}]: no {self.model_type} artifact "
            f"found under {MODEL_DIR}. Using statistical baseline."
        )

    # ------------------------------------------------------------------
    # Internal prediction helpers
    # ------------------------------------------------------------------

    def _date_for_day(self, day_index: int) -> datetime:
        return self.start_date + timedelta(days=day_index)

    def _raw_predict(self, day_index: int) -> float:
        """Raw model or baseline prediction (no external factor applied).

        After a successful model prediction the result is appended to the
        rolling sales buffer so future lag features stay up to date.
        """
        date = self._date_for_day(day_index)

        if self._using_model and self._model is not None:
            try:
                if self.model_type == "lgbm":
                    features = _build_lgbm_features(day_index, date)
                    pred = self._model.predict(features)
                    result = float(max(0.0, pred[0]))
                else:  # xgb
                    import xgboost as xgb  # type: ignore
                    dmat = _build_xgb_row(
                        day_index, date,
                        self._xgb_features,   # type: ignore[arg-type]
                        self._sales_buffer,
                    )
                    pred = self._model.predict(dmat)
                    result = float(max(0.0, pred[0]))

                # Roll the buffer forward with today's prediction
                self._sales_buffer.append(result)
                return result

            except Exception as exc:
                warnings.warn(
                    f"DemandGenerator[{self.store_id}] predict failed: {exc}. "
                    f"Falling back to statistical baseline for this call."
                )

        baseline_result = self._baseline.predict(day_index, date)
        # Also update buffer from baseline so lag features stay consistent
        self._sales_buffer.append(baseline_result)
        return baseline_result

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def get_demand(self, day_index: int, category: str = "default") -> float:
        """Return expected demand for simulation day *day_index*.

        Applies the ExternalFactors category multiplier so holidays / weather
        are reflected in the returned value.

        Parameters
        ----------
        day_index : int
            Zero-based simulation day offset from start_date.
        category : str
            Product category passed to ExternalFactors for the multiplier.
        """
        date       = self._date_for_day(day_index)
        raw        = self._raw_predict(day_index)
        factors    = self.external_factors.generate(date)
        multiplier = factors.get_demand_multiplier(category)
        return raw * multiplier

    def get_forecast_range(
        self,
        start_day: int,
        days: int = 14,
        category: str = "default",
    ) -> List[float]:
        """Return demand forecasts for *days* consecutive days from *start_day*.

        Used by SmartInventoryAgent to compute reorder quantities.

        Parameters
        ----------
        start_day : int
            First day of the forecast window (simulation day index).
        days : int
            Number of days to forecast.  Defaults to 14.
        category : str
            Product category multiplier passed to get_demand().

        Note
        ----
        Calling this method advances the internal sales buffer by *days*
        entries.  If you need a "peek" forecast without side-effects, call
        get_demand() on a cloned instance instead.
        """
        return [self.get_demand(start_day + i, category=category) for i in range(days)]

    @property
    def using_trained_model(self) -> bool:
        """True if a real model artifact was loaded; False if using baseline."""
        return self._using_model

    @property
    def sales_buffer_snapshot(self) -> List[float]:
        """Read-only snapshot of the current rolling sales buffer (last 28 days)."""
        return list(self._sales_buffer)